spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service