server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:''}
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    open-in-view: false
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:111}
    username: ${MAIL_USERNAME:email@example.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
    path: '/api/v3/api-docs'
  swagger-ui:
    path: '/api/swagger-ui.html'
    configUrl: '/api/v3/api-docs/swagger-config'
    disable-swagger-default-url: true
    url: /open-api.yml

jwt:
  secret-key: ${JWT_SECRET_KEY:jwtkey}
