logging:
  file:
    name: app.log
server:
  address: 0.0.0.0
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT}
spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true