logging:
  file:
    name: app.log
server:
  address: 0.0.0.0
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: 9091
spring:
  datasource:
    password: ${DB_PW}
    url: ${DB_URL}
    username: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true