spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
