name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  USER_PW: ${{ secrets.USER_PW }}
  USER_PLUS_DROPLET: ${{ secrets.USER_PLUS_DROPLET }}
  DROPLET_PORT: ${{ secrets.DROPLET_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CI/CD ongoing... :eyes: بسم الله الرحمن الرحيم'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fahrican/get-things-done-api:latest
          context: .

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':white_check_mark: pushed fahrican/get-things-done-api:latest to docker hub... https://hub.docker.com/repository/docker/fahrican/get-things-done-api'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'Digital Ocean deployment started... :grimacing: :crossed_fingers: ان شاء الله خير'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v3
      - run: ./.github/workflows/deploy.sh