#name: Build & Deploy
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#env:
#  # Java
#  JAVA_VERSION: 1.18
#  # DockerHub
#  DOCKER_HUB_USERNAME: fahrican
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy Backend
#        uses: appleboy/ssh-action@v0.1.2
#        with:
#          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
#          key: ${{secrets.SSH_KEY}} # Private or public key of the server
#          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
#
#          script: |
#            mkdir test
#            cd test
#            git clone https://github.com/fahrican/get_things_done.git
#            echo 'Deployment successful to digital ocean'
#
#      - name: Docker Login
#          uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
#          with:
#            username: ${{ env.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
